services:
  - type: web
    name: biomarket
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: gunicorn biomarket.wsgi:application --preload
    preDeployCommand: |
      python manage.py migrate --noinput
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: biomarket.settings
      - key: PYTHON_VERSION
        value: 3.12.11
